title = "zero config"

[feeds]
[feeds.global]
#patterns = [""]

[[feeds.items]]
name = "zeroday initiative - published"
url = "https://www.zerodayinitiative.com/rss/published/"
pattern = "cvss\\sscore\\s[1-9]\\.\\d"
depth = 10

[[feeds.items]]
name = "zeroday initiative - upcoming"
url = "https://www.zerodayinitiative.com/rss/upcoming/"
pattern = "cvss\\sscore\\s[1-9]\\.\\d"
depth = 25

[[feeds.items]]
name = "Threat Post - Cloud Security"
url = "https://threatpost.com/category/cloud-security/feed"
pattern = "AWS|Amazon|terraform|spinnaker|google"
depth = 5

[[feeds.items]]
name = "Threat Post - Vulnerabilities"
url = "https://threatpost.com/category/vulnerabilities/feed"
pattern = "Amazon|AWS|ruby|node|golang|python|typescript"
depth = 100
