title = "zero config"

[feeds]
[feeds.global]
#patterns = [""]

[[feeds.items]]
name = "zeroday initiative - published"
url = "https://www.zerodayinitiative.com/rss/published/"
pattern = ".*"
depth = 10

[[feeds.items]]
name = "zeroday initiative - upcoming"
url = "https://www.zerodayinitiative.com/rss/upcoming/"
pattern = ".*"
depth = 200
