# https://taskfile.dev

version: '3'
tasks:
  default:
    cmds:
      - golangci-lint run ./...

  json:
    desc: "Generate json unmarshalling for structs"
    cmds:
      - easyjson zero/feed.go
      - easyjson zero/match.go
      - easyjson zero/results.go
    sources:
      - zero/*.go
    generates:
      - zero/match_easyjson.go
      - zero/feed_easyjson.go
      - zero/results_easyjson.go
    method: checksum
