// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package zero

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD77e0694DecodeGithubComBrittonhayesZeroZero(in *jlexer.Lexer, out *Provider) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "depth":
			out.Depth = int(in.Int())
		case "pattern":
			out.Pattern = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD77e0694EncodeGithubComBrittonhayesZeroZero(out *jwriter.Writer, in Provider) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"depth\":"
		out.RawString(prefix)
		out.Int(int(in.Depth))
	}
	{
		const prefix string = ",\"pattern\":"
		out.RawString(prefix)
		out.String(string(in.Pattern))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Provider) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD77e0694EncodeGithubComBrittonhayesZeroZero(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Provider) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD77e0694EncodeGithubComBrittonhayesZeroZero(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Provider) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD77e0694DecodeGithubComBrittonhayesZeroZero(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Provider) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD77e0694DecodeGithubComBrittonhayesZeroZero(l, v)
}
